/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: VR.Space (https://sketchfab.com/vrspace01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/variety-of-books-9ecd80af3b7e4cd59efb4c141511a55b
Title: Variety of Books
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Books(props) {
  const { nodes, materials } = useGLTF('/read/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.012}>
        <mesh geometry={nodes.Cube_books_0.geometry} material={materials.books} rotation={[-Math.PI / 3, -0, -1.5]} scale={103} />
      </group>
    </group>
  )
}

useGLTF.preload('/read/scene.gltf')
