/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: shotorokiartz (https://sketchfab.com/shotorokiartz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-Cubes/3x3-rubiks-cube-2282c3a067914a60b570217a22a302cf
Title: 3x3 Rubik's Cube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cube(props) {
  const { nodes, materials } = useGLTF('/cube/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01} rotation={[0.7,0.7,-16]}>
        <group scale={1.5}>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube001_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube001_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube001_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube001_red_0.geometry} material={materials.material} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube002_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube002_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube002_red_0.geometry} material={materials.material} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube029_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube029_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube029_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube029_red_0.geometry} material={materials.material} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube030_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube030_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube030_blue_0.geometry} material={materials.blue} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube031_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube031_white_0.geometry} material={materials.white} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube032_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube032_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube032_white_0.geometry} material={materials.white} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube033_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube033_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube033_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube033_orange_0.geometry} material={materials.orange} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube034_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube034_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube034_orange_0.geometry} material={materials.orange} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube035_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube035_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube035_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube035_orange_0.geometry} material={materials.orange} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube036_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube036_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube036_blue_0.geometry} material={materials.blue} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube037_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube037_red_0.geometry} material={materials.material} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube038_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube038_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube038_red_0.geometry} material={materials.material} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube039_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube039_blue_0.geometry} material={materials.blue} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube040_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube040_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube040_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cube040_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube040_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube040_orange_0.geometry} material={materials.orange} />
            <mesh geometry={nodes.Cube040_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube041_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube041_green_0.geometry} material={materials.green} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube042_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube042_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube042_orange_0.geometry} material={materials.orange} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube043_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube043_orange_0.geometry} material={materials.orange} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube044_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube044_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube044_orange_0.geometry} material={materials.orange} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube045_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube045_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube045_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube045_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube046_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube046_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube046_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube047_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube047_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube047_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube047_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube048_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube048_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube048_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube049_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube049_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube050_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube050_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube050_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube051_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube051_blue_0.geometry} material={materials.blue} />
            <mesh geometry={nodes.Cube051_orange_0.geometry} material={materials.orange} />
            <mesh geometry={nodes.Cube051_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube052_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube052_orange_0.geometry} material={materials.orange} />
            <mesh geometry={nodes.Cube052_yellow_0.geometry} material={materials.yellow} />
          </group>
          <group scale={0.333}>
            <mesh geometry={nodes.Cube053_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Cube053_green_0.geometry} material={materials.green} />
            <mesh geometry={nodes.Cube053_orange_0.geometry} material={materials.orange} />
            <mesh geometry={nodes.Cube053_yellow_0.geometry} material={materials.yellow} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cube/scene.gltf')
