/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: krishna_hxcker (https://sketchfab.com/krishna_hxcker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flipperzero-hacking-tool-2c7d2ac3d7d54d3883ea76158fc288c3
Title: Flipperzero hacking tool
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cyber(props) {
  const { nodes, materials } = useGLTF('/cyber/scene.gltf')
  return (
    <group {...props} dispose={null} scale={0.08}>
      <group position={[-18.07, 2.628, -4.148]} rotation={[-10.114, -118, -4.134]} scale={[1,1,1]} fov={39}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.New_material_008} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.New_material_009} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.New_material_009} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.New_material_009} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.New_material_012} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.New_material_012} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.New_material_013} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.New_material_014} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.New_material_015} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.New_material_015} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.New_material_007} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.New_material_015} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.New_material_011} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.New_material_003} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.New_material_003} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.New_material_010} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.New_material_008} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.New_material_008} />
      </group>
    </group>
  )
}

useGLTF.preload('/cyber/scene.gltf')
