/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Imagigoo (https://sketchfab.com/Imagigoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-mac-book-pro-laptop-344a472d2e3e45f9af68079fc0336d17
Title: (Free) Mac Book Pro - Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/dev/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.08}>
        <group rotation={[-Math.PI / 2.5, 0, 0]} scale={70} >
          <group position={[0.006, 0.093, 0.027]} scale={0.259}>
            <mesh geometry={nodes.Cube012_key_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube012_key_0_1.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube012_key_0_2.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube012_key002_0.geometry} material={materials['key.002']} />
            <mesh geometry={nodes.Cube012_Material026_0.geometry} material={materials['Material.026']} />
          </group>
          <group position={[-0.4, 0.213, 0.026]} scale={[0.001, 0.001, 0]}>
            <mesh geometry={nodes.Cube013_body_0.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_1.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_2.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_3.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_4.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_5.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_6.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_7.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_8.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_9.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_10.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_11.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_12.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_13.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_14.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_15.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_16.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_17.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube013_body_0_18.geometry} material={materials.body} />
          </group>
          <group position={[0.321, 0.213, 0.026]} scale={[0.001, 0.001, 0]}>
            <mesh geometry={nodes.Cube014_body_0.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_1.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_2.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_3.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_4.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_5.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_6.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_7.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_body_0_8.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube014_black001_0.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_1.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_2.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_3.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_4.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_5.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_6.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_7.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_8.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_9.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_10.geometry} material={materials['black.001']} />
            <mesh geometry={nodes.Cube014_black001_0_11.geometry} material={materials['black.001']} />
          </group>
          <group position={[0, 0.003, 0.017]} rotation={[-0.016, 0, 0]}>
            <mesh geometry={nodes.Cube021_body_0.geometry} material={materials.body} />
            <mesh geometry={nodes.Cube021_Dark_0.geometry} material={materials.Dark} />
            <mesh geometry={nodes.Cube021_Material028_0.geometry} material={materials['Material.028']} />
          </group>
          <group position={[0, 0.28, 0.027]} rotation={[-0.263, 0, 0]} scale={0.259}>
            <group position={[0.001, 0.015, -0.05]} rotation={[1.807, 0, 0]} scale={1.06}>
              <mesh geometry={nodes.Cube016_screen_0.geometry} material={materials.screen} />
              <mesh geometry={nodes.Cube016_black002_0.geometry} material={materials['black.002']} />
              <mesh geometry={nodes.Cube016_body_0.geometry} material={materials.body} />
              <mesh geometry={nodes.Cube016_dark_0.geometry} material={materials.dark} />
              <mesh geometry={nodes.Cube016_glass002_0.geometry} material={materials['glass.002']} />
              <mesh geometry={nodes.Cube016_Material024_0.geometry} material={materials['Material.024']} />
              <mesh geometry={nodes.Cube016_Material025_0.geometry} material={materials['Material.025']} />
              <mesh geometry={nodes.Cube016_glass003_0.geometry} material={materials['glass.003']} />
              <mesh geometry={nodes['Cube016_Apple-logo_0'].geometry} material={materials['Apple-logo']} />
            </group>
            <mesh geometry={nodes.Text003_Material029_0.geometry} material={materials['Material.029']} position={[0.01, -0.011, 0.063]} rotation={[1.806, 0, 0]} scale={[0.044, 0.049, 0.045]} />
          </group>
          <mesh geometry={nodes.Cube010_black_0.geometry} material={materials.black} position={[-0.392, 0.188, 0.018]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]} />
          <mesh geometry={nodes.Cube011_key_0.geometry} material={materials.material} position={[0.14, 0.167, 0.027]} scale={0.259} />
          <mesh geometry={nodes.Cube015_body_0.geometry} material={materials.body} position={[0, -0.149, 0.025]} rotation={[0.001, 0, 0]} scale={0.121} />
          <mesh geometry={nodes.Cube017_black_0.geometry} material={materials.black} position={[-0.392, 0.188, 0.02]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]} />
          <mesh geometry={nodes.Cube018_black003_0.geometry} material={materials['black.003']} position={[-0.393, 0.183, 0.019]} rotation={[0.001, 0, 0]} scale={[0.006, 0.008, 0.004]} />
          <mesh geometry={nodes.Cube019_black_0.geometry} material={materials.black} position={[-0.392, 0.227, 0.018]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]} />
          <mesh geometry={nodes.Cube020_black_0.geometry} material={materials.black} position={[-0.392, 0.227, 0.02]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]} />
          <mesh geometry={nodes.Cube022_black003_0.geometry} material={materials['black.003']} position={[-0.393, 0.222, 0.019]} rotation={[0.001, 0, 0]} scale={[0.006, 0.008, 0.004]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dev/scene.gltf')
